import type { Article, Tool, Founder, FundingRound, Book, Video, Resource } from "@/types";

// ─────────────────────────────────────────
// ARTICLES
// ─────────────────────────────────────────
export const featuredArticle: Article = {
  id: "1",
  slug: "openai-gpt5-changes-everything",
  title: "GPT-5 Is Here: Why Every Founder Needs to Rethink Their Product Strategy Today",
  excerpt:
    "OpenAI's latest model doesn't just write better — it reasons, plans, and executes. Here's what this means for startups building on AI infrastructure.",
  category: "AI",
  author: "Maya Patel",
  authorSlug: "maya-patel",
  authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format",
  publishedAt: "July 31, 2026",
  readingTime: 8,
  image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&h=700&fit=crop&auto=format",
  featured: true,
  tags: ["OpenAI", "GPT-5", "AI Strategy", "Founders"],
};

export const heroSideArticles: Article[] = [
  {
    id: "2",
    slug: "sequoia-raises-2b-ai-fund",
    title: "Sequoia Quietly Raises $2 Billion AI-Focused Fund — Biggest in a Decade",
    excerpt: "The legendary VC firm is doubling down on artificial intelligence with an unprecedented new fund targeting early-stage AI infrastructure startups.",
    category: "Funding",
    author: "James Wright",
    authorSlug: "james-wright",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 5,
    image: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "3",
    slug: "anthropic-claude-4-enterprise",
    title: "Anthropic's Claude 4 Is Taking the Enterprise Market by Storm",
    excerpt: "Fortune 500 companies are ditching legacy software and rebuilding workflows entirely around Claude 4's agentic capabilities.",
    category: "AI",
    author: "Sarah Chen",
    authorSlug: "sarah-chen",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "4",
    slug: "stripe-valuation-100-billion",
    title: "Stripe Hits $100B Valuation After Record-Breaking Quarter",
    excerpt: "The payments giant processes $1 trillion annually and is now preparing for what insiders say could be the decade's largest tech IPO.",
    category: "Startups",
    author: "David Park",
    authorSlug: "david-park",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 4,
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "5",
    slug: "founders-who-built-billion-dollar-companies-under-30",
    title: "The 12 Founders Who Built Billion-Dollar Companies Before Turning 30",
    excerpt: "A new generation of hyper-focused founders is compressing the timeline from zero to unicorn — here's what sets them apart.",
    category: "Founders",
    author: "Priya Sharma",
    authorSlug: "priya-sharma",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 10,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop&auto=format",
  },
];

export const topPicksArticles: Article[] = [
  {
    id: "6",
    slug: "elon-musk-xai-funding",
    title: "xAI's Grok 3 Beats GPT-4o on Every Benchmark — Elon Says It's Just Getting Started",
    excerpt: "The competition in large language models is intensifying. Musk's AI lab has produced a model that rivals OpenAI across reasoning, coding, and creative tasks.",
    category: "AI",
    author: "Marcus Johnson",
    authorSlug: "marcus-johnson",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 7,
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=500&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "7",
    slug: "sam-altman-world-id-expansion",
    title: "Sam Altman's World ID Reaches 10 Million Users",
    excerpt: "The biometric identity network is expanding rapidly as digital proof-of-personhood becomes critical infrastructure.",
    category: "Technology",
    author: "Emily Zhang",
    authorSlug: "emily-zhang",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 5,
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "8",
    slug: "india-startup-ecosystem-2026",
    title: "India's Startup Ecosystem Just Crossed $500B in Total Value",
    excerpt: "With 140 unicorns and counting, India's founders are building for the world — not just for local markets.",
    category: "Startups",
    author: "Rohan Gupta",
    authorSlug: "rohan-gupta",
    authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1573079081538-23b4fc1d0073?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "9",
    slug: "notion-ai-new-features",
    title: "Notion AI Just Got Dramatically Smarter — And It's Threatening Every Productivity App",
    excerpt: "The workspace tool's new AI features can manage entire projects, write code, and coordinate teams without human intervention.",
    category: "Technology",
    author: "Amy Liu",
    authorSlug: "amy-liu",
    authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 4,
    image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "10",
    slug: "a16z-state-of-ai-2026",
    title: "Andreessen Horowitz Releases State of AI 2026: The Most Important Charts",
    excerpt: "The landmark annual report reveals the tipping points, the winners, the losers, and what comes next in the global AI race.",
    category: "AI",
    author: "Tom Bradley",
    authorSlug: "tom-bradley",
    authorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 28, 2026",
    readingTime: 12,
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&h=400&fit=crop&auto=format",
  },
];

export const founderArticles: Article[] = [
  {
    id: "11",
    slug: "jensen-huang-decade-of-ai",
    title: "Jensen Huang on NVIDIA's Decade of Risk: 'Everyone Said We Were Crazy. We Were Right.'",
    excerpt: "In this rare long-form interview, the NVIDIA CEO reflects on the bets that changed everything and the new ones he's making for the next decade.",
    category: "Founders",
    author: "Maya Patel",
    authorSlug: "maya-patel",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 15,
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=900&h=600&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "12",
    slug: "melanie-perkins-canva-story",
    title: "How Melanie Perkins Turned 100 Rejections Into a $40B Design Empire",
    excerpt: "The Canva co-founder's story is a masterclass in persistence, product intuition, and building for the masses.",
    category: "Founders",
    author: "James Wright",
    authorSlug: "james-wright",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 9,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "13",
    slug: "brian-chesky-airbnb-redesign",
    title: "Brian Chesky's $100B Lesson: 'Delete Your Roadmap and Start with the User'",
    excerpt: "Airbnb's radical company redesign — and how its CEO is now teaching the philosophy to a new generation of founders.",
    category: "Founders",
    author: "Sarah Chen",
    authorSlug: "sarah-chen",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 7,
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "14",
    slug: "dara-khosrowshahi-uber-turnaround",
    title: "Uber's Quiet Comeback: How Dara Khosrowshahi Repaired a Broken Culture",
    excerpt: "Five years ago, Uber was a scandal-ridden mess. Today it's one of the most profitable companies in Silicon Valley.",
    category: "Founders",
    author: "David Park",
    authorSlug: "david-park",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 28, 2026",
    readingTime: 8,
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "15",
    slug: "tobi-lutke-shopify-ai-future",
    title: "Tobi Lütke: 'Every Shopify Merchant Will Have a Personal AI CFO Within Two Years'",
    excerpt: "The Shopify CEO is rewriting his company's future around AI agents that run businesses autonomously.",
    category: "Founders",
    author: "Amy Liu",
    authorSlug: "amy-liu",
    authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 27, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&auto=format",
  },
];

export const aiArticles: Article[] = [
  {
    id: "16",
    slug: "ai-agents-replace-knowledge-workers",
    title: "The Agent Economy: How AI Is Replacing Knowledge Workers Faster Than Anyone Predicted",
    excerpt: "Autonomous AI agents are handling legal research, financial analysis, and software engineering at scale.",
    category: "AI",
    author: "Marcus Johnson",
    authorSlug: "marcus-johnson",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 11,
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=700&h=450&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "17",
    slug: "google-gemini-ultra-2-launch",
    title: "Google Gemini Ultra 2 Just Launched — Is This the End of OpenAI's Lead?",
    excerpt: "DeepMind's latest model scores higher on every benchmark, but can Google's enterprise distribution catch up?",
    category: "AI",
    author: "Emily Zhang",
    authorSlug: "emily-zhang",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "18",
    slug: "ai-music-tools-2026",
    title: "AI Music Tools Are Generating $10M Songs. What Does This Mean for the Industry?",
    excerpt: "Suno, Udio, and a dozen new entrants are creating chart-topping music without a single human musician.",
    category: "AI",
    author: "Priya Sharma",
    authorSlug: "priya-sharma",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 7,
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "19",
    slug: "mistral-open-source-ai-wins",
    title: "Mistral's Open-Source Bet Is Paying Off — Enterprises Are Choosing Privacy Over Power",
    excerpt: "The French AI lab's decision to open-source its models is attracting privacy-conscious enterprises who want control.",
    category: "AI",
    author: "Tom Bradley",
    authorSlug: "tom-bradley",
    authorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 5,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&auto=format",
  },
];

export const makeMoneyArticles: Article[] = [
  {
    id: "20",
    slug: "build-saas-with-ai-2026",
    title: "How to Build and Launch a SaaS in 7 Days Using AI Tools — Step-by-Step",
    excerpt: "The complete playbook for solo founders who want to go from idea to paying customers using GPT-4, Cursor, and Supabase.",
    category: "Make Money with AI",
    author: "Rohan Gupta",
    authorSlug: "rohan-gupta",
    authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 14,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "21",
    slug: "ai-freelancing-10k-month",
    title: "The Freelancer's AI Toolkit: How to Earn $10K/Month Offering AI Services",
    excerpt: "Real strategies from 50 freelancers who pivoted to AI-powered services and hit 5-figure monthly revenue.",
    category: "Make Money with AI",
    author: "Amy Liu",
    authorSlug: "amy-liu",
    authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 8,
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "22",
    slug: "ai-content-agency-guide",
    title: "Start an AI Content Agency in 30 Days: The Complete 2026 Guide",
    excerpt: "From landing your first client to scaling to a 10-person operation — all using AI as your core infrastructure.",
    category: "Make Money with AI",
    author: "Marcus Johnson",
    authorSlug: "marcus-johnson",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 11,
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "23",
    slug: "prompt-engineering-career",
    title: "Prompt Engineering Is Now a $200K Career — Here's How to Get In",
    excerpt: "Top companies are paying premium salaries for prompt engineers. This guide explains exactly what skills you need.",
    category: "Make Money with AI",
    author: "Sarah Chen",
    authorSlug: "sarah-chen",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 28, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1573495612937-f01934eeaaa7?w=600&h=400&fit=crop&auto=format",
  },
];

export const startupArticles: Article[] = [
  {
    id: "24",
    slug: "linear-builds-billion-dollar-tool",
    title: "Linear Built a Billion-Dollar Project Tool with a Team of 50 and Zero Sales Reps",
    excerpt: "The anti-bloat philosophy of Linear's founders is proving that restraint and taste can be a moat in the software market.",
    category: "Startups",
    author: "Emily Zhang",
    authorSlug: "emily-zhang",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 9,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "25",
    slug: "figma-adobe-acquisition-aftermath",
    title: "One Year After the Adobe Deal Collapsed, Figma Is Stronger Than Ever",
    excerpt: "Rather than implode, Figma's independence has fueled a product renaissance and a $20B secondary market valuation.",
    category: "Startups",
    author: "Maya Patel",
    authorSlug: "maya-patel",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 7,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "26",
    slug: "perplexity-ai-vs-google",
    title: "Perplexity AI Is Challenging Google's 25-Year Monopoly on Search — and Winning",
    excerpt: "The answer engine has reached 100 million users and is stealing search queries from Google at an alarming rate.",
    category: "Startups",
    author: "James Wright",
    authorSlug: "james-wright",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 8,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "27",
    slug: "cursor-ai-ide-billion-users",
    title: "Cursor Is Redefining How Developers Write Code — and It's Growing Faster Than GitHub",
    excerpt: "The AI-powered IDE hit 1 million paid users faster than any developer tool in history.",
    category: "Startups",
    author: "David Park",
    authorSlug: "david-park",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 5,
    image: "https://images.unsplash.com/photo-1537432376769-00f5c2f4c8d2?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "28",
    slug: "vercel-new-frontend-cloud",
    title: "Vercel Is Building the Frontend Cloud — And Every Startup Should Be Paying Attention",
    excerpt: "v0, AI SDK, and the new infrastructure layer are positioning Vercel as the AWS of the frontend world.",
    category: "Startups",
    author: "Priya Sharma",
    authorSlug: "priya-sharma",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 28, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&auto=format",
  },
];

export const businessArticles: Article[] = [
  {
    id: "29",
    slug: "remote-work-is-back",
    title: "Remote Work Isn't Dead — But It Looks Completely Different in 2026",
    excerpt: "The post-pandemic remote work revolution has matured into a disciplined, async-first operating model.",
    category: "Business",
    author: "Tom Bradley",
    authorSlug: "tom-bradley",
    authorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 7,
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=400&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "30",
    slug: "product-market-fit-signals",
    title: "10 Signals That Tell You When You've Found Product-Market Fit",
    excerpt: "Founders often miss the signs of PMF because they're looking for the wrong things.",
    category: "Business",
    author: "Marcus Johnson",
    authorSlug: "marcus-johnson",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 5,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "31",
    slug: "fundraising-deck-mistakes",
    title: "The 15 Fundraising Deck Mistakes That Kill Your Deal in the First 5 Slides",
    excerpt: "Three partners at top VC firms share the exact slide patterns that make them close their laptop.",
    category: "Business",
    author: "Rohan Gupta",
    authorSlug: "rohan-gupta",
    authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 8,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "32",
    slug: "b2b-sales-ai-tools",
    title: "How AI Is Transforming B2B Sales: The Tools That Are Actually Working",
    excerpt: "Sales teams using AI tools are closing deals 40% faster. Here's the exact stack they're using.",
    category: "Business",
    author: "Emily Zhang",
    authorSlug: "emily-zhang",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 28, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop&auto=format",
  },
];

export const technologyArticles: Article[] = [
  {
    id: "33",
    slug: "quantum-computing-2026-update",
    title: "Quantum Computing Just Hit a Milestone That Scientists Said Was Decades Away",
    excerpt: "IBM's new quantum processor achieved error correction at scale — changing the timeline for practical quantum advantage.",
    category: "Technology",
    author: "Maya Patel",
    authorSlug: "maya-patel",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 31, 2026",
    readingTime: 9,
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=700&h=450&fit=crop&auto=format",
    featured: true,
  },
  {
    id: "34",
    slug: "apple-vision-pro-enterprise",
    title: "Apple Vision Pro Is Quietly Becoming the Best Enterprise Device in History",
    excerpt: "Forget the consumer launch — enterprise adoption is surging and the use cases are extraordinary.",
    category: "Technology",
    author: "James Wright",
    authorSlug: "james-wright",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 30, 2026",
    readingTime: 6,
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "35",
    slug: "ev-battery-breakthrough-2026",
    title: "Solid-State Batteries Are Finally Here — And They Change Everything for EVs",
    excerpt: "Toyota's new solid-state battery promises 1,000-mile range and 10-minute charging. It's real, and it ships in 2027.",
    category: "Technology",
    author: "David Park",
    authorSlug: "david-park",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 29, 2026",
    readingTime: 7,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "36",
    slug: "web3-is-back",
    title: "Web3 Is Back — But This Time, It's Actually Building Real Things",
    excerpt: "After years of speculation, blockchain technology is quietly finding genuine product-market fit in supply chain and identity.",
    category: "Technology",
    author: "Priya Sharma",
    authorSlug: "priya-sharma",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format",
    publishedAt: "July 28, 2026",
    readingTime: 5,
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=400&fit=crop&auto=format",
  },
];

// ─────────────────────────────────────────
// TOOLS
// ─────────────────────────────────────────
export const topTools: Tool[] = [
  {
    id: "1",
    slug: "cursor-ai",
    name: "Cursor",
    tagline: "The AI-first code editor",
    category: "Coding",
    logo: "https://images.unsplash.com/photo-1537432376769-00f5c2f4c8d2?w=80&h=80&fit=crop&auto=format",
    pricing: "Free / $20/mo",
    pricingType: "freemium",
    url: "https://cursor.sh",
    description: "AI-powered IDE that understands your codebase and writes code with you.",
  },
  {
    id: "2",
    slug: "claude-ai",
    name: "Claude",
    tagline: "Anthropic's AI assistant",
    category: "AI Assistant",
    logo: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=80&h=80&fit=crop&auto=format",
    pricing: "Free / $20/mo",
    pricingType: "freemium",
    url: "https://claude.ai",
    description: "Constitutional AI assistant that excels at analysis, writing, and reasoning.",
  },
  {
    id: "3",
    slug: "midjourney",
    name: "Midjourney",
    tagline: "AI image generation",
    category: "Image Generation",
    logo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80&h=80&fit=crop&auto=format",
    pricing: "$10/mo",
    pricingType: "paid",
    url: "https://midjourney.com",
    description: "World-class AI image generation with exceptional aesthetic quality.",
  },
  {
    id: "4",
    slug: "perplexity-ai",
    name: "Perplexity",
    tagline: "AI-powered search engine",
    category: "Search",
    logo: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=80&h=80&fit=crop&auto=format",
    pricing: "Free / $20/mo",
    pricingType: "freemium",
    url: "https://perplexity.ai",
    description: "Answer engine that searches the web and synthesizes real-time information.",
  },
  {
    id: "5",
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "AI built into your workspace",
    category: "Productivity",
    logo: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=80&h=80&fit=crop&auto=format",
    pricing: "$10/mo add-on",
    pricingType: "paid",
    url: "https://notion.so",
    description: "AI writing, summarization, and automation built into Notion workspaces.",
  },
  {
    id: "6",
    slug: "runway-ml",
    name: "Runway",
    tagline: "AI video generation",
    category: "Video",
    logo: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=80&h=80&fit=crop&auto=format",
    pricing: "$12/mo",
    pricingType: "paid",
    url: "https://runwayml.com",
    description: "Professional AI video generation and editing tools for creators.",
  },
  {
    id: "7",
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "AI voice cloning",
    category: "Audio",
    logo: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=80&h=80&fit=crop&auto=format",
    pricing: "Free / $5/mo",
    pricingType: "freemium",
    url: "https://elevenlabs.io",
    description: "Most realistic AI voice synthesis and cloning platform available.",
  },
  {
    id: "8",
    slug: "v0-vercel",
    name: "v0 by Vercel",
    tagline: "AI UI generation",
    category: "Development",
    logo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=80&h=80&fit=crop&auto=format",
    pricing: "Free / $20/mo",
    pricingType: "freemium",
    url: "https://v0.dev",
    description: "Generate React UI components from text prompts using shadcn/ui.",
  },
];

// ─────────────────────────────────────────
// FUNDING ROUNDS
// ─────────────────────────────────────────
export const fundingRounds: FundingRound[] = [
  {
    id: "1",
    startup: "Mistral AI",
    amount: "$600M",
    stage: "Series B",
    investors: ["General Catalyst", "Andreessen Horowitz", "Lightspeed"],
    country: "France 🇫🇷",
    date: "July 31, 2026",
    logo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=50&h=50&fit=crop&auto=format",
  },
  {
    id: "2",
    startup: "Harvey AI",
    amount: "$300M",
    stage: "Series C",
    investors: ["Sequoia Capital", "Google Ventures"],
    country: "USA 🇺🇸",
    date: "July 30, 2026",
    logo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=50&h=50&fit=crop&auto=format",
  },
  {
    id: "3",
    startup: "Anysphere (Cursor)",
    amount: "$900M",
    stage: "Series D",
    investors: ["a16z", "Thrive Capital", "OpenAI Fund"],
    country: "USA 🇺🇸",
    date: "July 29, 2026",
    logo: "https://images.unsplash.com/photo-1537432376769-00f5c2f4c8d2?w=50&h=50&fit=crop&auto=format",
  },
  {
    id: "4",
    startup: "Cohere",
    amount: "$500M",
    stage: "Series D",
    investors: ["NVIDIA", "Salesforce Ventures", "Oracle"],
    country: "Canada 🇨🇦",
    date: "July 28, 2026",
    logo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=50&h=50&fit=crop&auto=format",
  },
  {
    id: "5",
    startup: "Glean",
    amount: "$200M",
    stage: "Series E",
    investors: ["Kleiner Perkins", "Lightspeed", "Slack Fund"],
    country: "USA 🇺🇸",
    date: "July 27, 2026",
    logo: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=50&h=50&fit=crop&auto=format",
  },
  {
    id: "6",
    startup: "Writer",
    amount: "$200M",
    stage: "Series C",
    investors: ["ICONIQ Growth", "Balderton Capital"],
    country: "USA 🇺🇸",
    date: "July 26, 2026",
    logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=50&h=50&fit=crop&auto=format",
  },
];

// ─────────────────────────────────────────
// BOOKS
// ─────────────────────────────────────────
export const books: Book[] = [
  {
    id: "1",
    slug: "zero-to-one",
    title: "Zero to One",
    author: "Peter Thiel",
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=560&fit=crop&auto=format",
    summary: "Notes on startups and how to build the future. Thiel's contrarian view on competition, secrets, and monopoly.",
    affiliateUrl: "https://amzn.to/zerotoone",
    rating: 4.8,
    year: 2014,
  },
  {
    id: "2",
    slug: "the-hard-thing-about-hard-things",
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=560&fit=crop&auto=format",
    summary: "Building a business when there are no easy answers. Horowitz's raw, honest account of startup leadership.",
    affiliateUrl: "https://amzn.to/hardhings",
    rating: 4.7,
    year: 2014,
  },
  {
    id: "3",
    slug: "founders-at-work",
    title: "Founders at Work",
    author: "Jessica Livingston",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=560&fit=crop&auto=format",
    summary: "Interviews with founders of famous technology companies about the early days of their startups.",
    affiliateUrl: "https://amzn.to/foundersatwork",
    rating: 4.6,
    year: 2007,
  },
  {
    id: "4",
    slug: "the-lean-startup",
    title: "The Lean Startup",
    author: "Eric Ries",
    cover: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&h=560&fit=crop&auto=format",
    summary: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    affiliateUrl: "https://amzn.to/leanstartup",
    rating: 4.4,
    year: 2011,
  },
  {
    id: "5",
    slug: "shoe-dog",
    title: "Shoe Dog",
    author: "Phil Knight",
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=560&fit=crop&auto=format",
    summary: "A memoir by the creator of Nike. An honest, riveting story of the risks and vulnerabilities of building a company.",
    affiliateUrl: "https://amzn.to/shoedog",
    rating: 4.9,
    year: 2016,
  },
];

// ─────────────────────────────────────────
// VIDEOS
// ─────────────────────────────────────────
export const videos: Video[] = [
  {
    id: "1",
    slug: "how-to-build-ai-startup",
    title: "How to Build an AI Startup in 2026 — Full Breakdown",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=700&h=400&fit=crop&auto=format",
    duration: "45:12",
    channel: "Y Combinator",
    excerpt: "Paul Graham walks through the exact framework YC uses to evaluate AI startups — and what they're looking for in 2026.",
    publishedAt: "July 28, 2026",
  },
  {
    id: "2",
    slug: "jensen-huang-keynote",
    title: "Jensen Huang's GTC 2026 Keynote — Full",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=700&h=400&fit=crop&auto=format",
    duration: "2:14:08",
    channel: "NVIDIA",
    excerpt: "The complete NVIDIA GTC keynote featuring Blackwell Ultra, Project GROOT 2, and the future of physical AI.",
    publishedAt: "July 25, 2026",
  },
  {
    id: "3",
    slug: "vc-panel-ai-investing",
    title: "The AI Investment Landscape: A Panel of Top VCs",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=700&h=400&fit=crop&auto=format",
    duration: "58:34",
    channel: "All-In Podcast",
    excerpt: "Chamath, Jason, David, and Sacks debate which AI bets will win and what the next 5 years look like.",
    publishedAt: "July 22, 2026",
  },
  {
    id: "4",
    slug: "product-management-ai-era",
    title: "Product Management in the AI Era",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=700&h=400&fit=crop&auto=format",
    duration: "32:18",
    channel: "Lenny's Podcast",
    excerpt: "How the PM role is being redefined by AI — and what skills you need to stay relevant.",
    publishedAt: "July 19, 2026",
  },
];

// ─────────────────────────────────────────
// RESOURCES
// ─────────────────────────────────────────
export const resources: Resource[] = [
  {
    id: "1",
    slug: "pitch-deck-template",
    title: "Pitch Deck Template",
    type: "template",
    description: "A 15-slide pitch deck template used by YC founders to raise their seed rounds.",
    icon: "Presentation",
    downloadUrl: "#",
    free: true,
  },
  {
    id: "2",
    slug: "startup-financial-model",
    title: "Startup Financial Model",
    type: "template",
    description: "A complete 3-year financial model with revenue projections, burn rate, and runway calculator.",
    icon: "BarChart2",
    downloadUrl: "#",
    free: true,
  },
  {
    id: "3",
    slug: "product-roadmap-guide",
    title: "Product Roadmap Guide",
    type: "guide",
    description: "How to build a product roadmap that aligns engineering, design, and business objectives.",
    icon: "Map",
    downloadUrl: "#",
    free: true,
  },
  {
    id: "4",
    slug: "fundraising-checklist",
    title: "Fundraising Checklist",
    type: "checklist",
    description: "50-point checklist for founders preparing to raise a seed or Series A round.",
    icon: "CheckSquare",
    downloadUrl: "#",
    free: true,
  },
  {
    id: "5",
    slug: "ai-tools-directory",
    title: "AI Tools for Founders",
    type: "tool",
    description: "Curated directory of 200+ AI tools for startups — organized by category and use case.",
    icon: "Zap",
    downloadUrl: "#",
    free: true,
  },
  {
    id: "6",
    slug: "saas-metrics-guide",
    title: "SaaS Metrics Guide",
    type: "guide",
    description: "The definitive guide to SaaS metrics: ARR, MRR, churn, NPS, LTV/CAC and more.",
    icon: "TrendingUp",
    downloadUrl: "#",
    free: true,
  },
];

// ─────────────────────────────────────────
// BREAKING NEWS
// ─────────────────────────────────────────
export const breakingNews = [
  {
    id: "1",
    time: "10:45 AM",
    slug: "openai-gpt5",
    title: "🔴 BREAKING: OpenAI confirms GPT-5 general availability — prices drop 80%",
  },
  {
    id: "2",
    time: "09:30 AM",
    slug: "anthropic-series-f",
    title: "🔴 BREAKING: Anthropic raises $4B Series F at $40B valuation — largest AI round ever",
  },
  {
    id: "3",
    time: "08:15 AM",
    slug: "apple-ai-chip",
    title: "🔴 BREAKING: Apple announces AI chip that runs GPT-4-class models on-device",
  },
  {
    id: "4",
    time: "07:00 AM",
    slug: "meta-llama-4",
    title: "🔴 BREAKING: Meta releases Llama 4 — claims it beats GPT-4o on every benchmark",
  },
  {
    id: "5",
    time: "Yesterday",
    slug: "yc-w26-batch",
    title: "🔴 BREAKING: Y Combinator W26 batch revealed — 70% of companies are AI-first",
  },
];
